version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
  open-pull-requests-limit: 10
  labels:
  - dependencies
  commit-message:
    prefix: Fix
    prefix-development: chore
    include: scope
